package com.example.comeondoit.model

object DataTimeGrid {
    fun getTimeGrid(): List<TimeGrid> {
        return listOf(
            TimeGrid(
                "00:00",
                "01:00"
            ),
            TimeGrid(
                "01:00",
                "02:00"
            ),
            TimeGrid(
                "02:00",
                "03:00"
            ),
            TimeGrid(
                "03:00",
                "04:00"
            ),
            TimeGrid(
                "04:00",
                "05:00"
            ),
            TimeGrid(
                "05:00",
                "06:00"
            ),
            TimeGrid(
                "06:00",
                "07:00"
            ),
            TimeGrid(
                "07:00",
                "08:00"
            ),
            TimeGrid(
                "08:00",
                "09:00"
            ),
            TimeGrid(
                "09:00",
                "10:00"
            ),
            TimeGrid(
                "10:00",
                "11:00"
            ),
            TimeGrid(
                "11:00",
                "12:00"
            ),
            TimeGrid(
                "12:00",
                "13:00"
            ),
            TimeGrid(
                "13:00",
                "14:00"
            ),
            TimeGrid(
                "14:00",
                "15:00"
            ),
            TimeGrid(
                "15:00",
                "16:00"
            ),
            TimeGrid(
                "16:00",
                "17:00"
            ),
            TimeGrid(
                "17:00",
                "18:00"
            ),
            TimeGrid(
                "18:00",
                "19:00"
            ),
            TimeGrid(
                "19:00",
                "20:00"
            ),
            TimeGrid(
                "20:00",
                "21:00"
            ),
            TimeGrid(
                "21:00",
                "22:00"
            ),
            TimeGrid(
                "22:00",
                "23:00"
            ),
            TimeGrid(
                "23:00",
                "00:00"
            )
        )
    }
}
